ignoreFiles:
  - "**/*.min.css"

plugins:
  - stylelint-declaration-strict-value

overrides:
  - files: ["**/*.html"]
    customSyntax: postcss-html

rules:
  annotation-no-unknown: true
  at-rule-no-unknown: true
  at-rule-no-vendor-prefix: true
  block-no-empty: true
  color-hex-case: lower
  color-no-invalid-hex: true
  comment-no-empty: true
  custom-property-no-missing-var-function: true
  declaration-bang-space-after: never
  declaration-block-no-duplicate-custom-properties: true
  declaration-block-no-duplicate-properties: [true, {ignore: [consecutive-duplicates-with-different-values]}]
  declaration-block-semicolon-space-before: never
  declaration-colon-space-before: never
  declaration-property-value-no-unknown: true
  font-family-name-quotes: always-where-recommended
  font-family-no-duplicate-names: true
  font-family-no-missing-generic-family-keyword: true
  function-calc-no-unspaced-operator: true
  function-linear-gradient-no-nonstandard-direction: true
  function-max-empty-lines: 0
  function-name-case: lower
  function-no-unknown: true
  function-parentheses-newline-inside: never-multi-line
  function-url-quotes: always
  indentation: 2
  keyframe-block-no-duplicate-selectors: true
  keyframe-declaration-no-important: true
  length-zero-no-unit: true
  max-empty-lines: 1
  media-feature-colon-space-before: never
  media-feature-name-no-unknown: true
  media-feature-name-no-vendor-prefix: true
  media-feature-range-operator-space-after: always
  media-feature-range-operator-space-before: always
  named-grid-areas-no-invalid: true
  no-duplicate-at-import-rules: true
  no-empty-source: true
  no-eol-whitespace: true
  no-extra-semicolons: true
  no-invalid-double-slash-comments: true
  no-invalid-position-at-import-rule: true
  no-irregular-whitespace: true
  no-missing-end-of-source-newline: true
  number-leading-zero: never
  property-case: lower
  property-no-unknown: true
  property-no-vendor-prefix: true
  selector-attribute-quotes: always
  selector-list-comma-space-after: always-single-line
  selector-list-comma-space-before: never-single-line
  selector-max-empty-lines: 0
  selector-no-vendor-prefix: true
  selector-pseudo-class-case: lower
  selector-pseudo-class-no-unknown: true
  selector-pseudo-class-parentheses-space-inside: never
  selector-pseudo-element-case: lower
  selector-pseudo-element-colon-notation: double
  selector-pseudo-element-no-unknown: true
  selector-type-case: lower
  selector-type-no-unknown: [true, {ignore: [custom-elements]}]
  scale-unlimited/declaration-strict-value: [color, {ignoreValues: /^(inherit|transparent|unset|initial)$/}]
  shorthand-property-no-redundant-values: true
  string-no-newline: true
  string-quotes: double
  unit-case: lower
  unit-no-unknown: true
  value-list-max-empty-lines: 0
  value-no-vendor-prefix: [true, {ignoreValues: [box, inline-box]}]
