plugins:
  - stylelint-declaration-strict-value

overrides:
  - files: ["**/*.html"]
    customSyntax: postcss-html

rules:
  annotation-no-unknown: true
  at-rule-no-unknown: true
  at-rule-no-vendor-prefix: true
  block-no-empty: true
  color-no-invalid-hex: true
  comment-no-empty: true
  custom-property-no-missing-var-function: true
  declaration-block-no-duplicate-custom-properties: true
  declaration-block-no-duplicate-properties: [true, {ignore: [consecutive-duplicates-with-different-values]}]
  declaration-property-value-no-unknown: true
  font-family-name-quotes: always-where-recommended
  font-family-no-duplicate-names: true
  font-family-no-missing-generic-family-keyword: true
  function-calc-no-unspaced-operator: true
  function-linear-gradient-no-nonstandard-direction: true
  function-name-case: lower
  function-no-unknown: true
  function-url-quotes: always
  keyframe-block-no-duplicate-selectors: true
  keyframe-declaration-no-important: true
  length-zero-no-unit: true
  media-feature-name-no-unknown: true
  media-feature-name-no-vendor-prefix: true
  named-grid-areas-no-invalid: true
  no-duplicate-at-import-rules: true
  no-duplicate-selectors: null # todo: true
  no-empty-source: true
  no-invalid-double-slash-comments: true
  no-invalid-position-at-import-rule: true
  no-irregular-whitespace: true
  property-no-unknown: true
  scale-unlimited/declaration-strict-value: [color, {ignoreValues: /^(inherit|transparent|unset|initial|currentcolor)$/, disableFix: true}]
  selector-attribute-quotes: always
  selector-no-vendor-prefix: true
  selector-pseudo-class-no-unknown: true
  selector-pseudo-element-colon-notation: double
  selector-pseudo-element-no-unknown: true
  selector-type-case: lower
  selector-type-no-unknown: [true, {ignore: [custom-elements]}]
  shorthand-property-no-redundant-values: true
  string-no-newline: true
  unit-no-unknown: true
  value-no-vendor-prefix: [true, {ignoreValues: [box, inline-box]}]
